import type { DocType, DocStatus, ShippingMethod } from "@contracts/types";

/* ------------------------------------------------------------------ */
/* Baked demo data (design-delta §6): every demo works with an empty   */
/* or unreachable DB. Live tRPC data is merged over these fallbacks.   */
/* ------------------------------------------------------------------ */

export type DemoDocType = DocType | "INV" | "PL" | "GP" | "DG" | "SB" | "CLP";

export interface DemoDoc {
  /** Stable key for React + drawer state. */
  key: string;
  docType: DemoDocType;
  /** Human doc number, e.g. "2841 9912 4471". */
  docNo: string;
  status: DocStatus;
  /** Minutes of validity left (EWB only); null when not time-bound. */
  validMinutesLeft: number | null;
  /** Total validity window in minutes (for bar math). */
  validMinutesTotal: number | null;
  /** Numeric DB id when the doc came from tRPC. */
  dbId?: number;
  /** Extra mono line shown under the badge label. */
  note?: string;
}

export const DOC_TYPE_LABEL: Record<string, string> = {
  EWB: "E-WAY BILL",
  IRN: "E-INVOICE IRN",
  INV: "TAX INVOICE",
  BOL: "BILL OF LADING",
  AWB: "AIR WAYBILL",
  LR: "LORRY RECEIPT",
  RR: "RAILWAY RECEIPT",
  PL: "PACKING LIST",
  GP: "GATE PASS",
  DG: "DG DECLARATION",
  SB: "SHIPPING BILL",
  CLP: "CONTAINER LOAD PLAN",
};

export const DEMO_DOCS: DemoDoc[] = [
  {
    key: "ewb-valid",
    docType: "EWB",
    docNo: "2841 9912 4471",
    status: "valid",
    validMinutesLeft: 22 * 60 + 14,
    validMinutesTotal: 5 * 24 * 60,
    note: "440 KM · WH-MUM-01 → DEL-NCR",
  },
  {
    key: "ewb-expiring",
    docType: "EWB",
    docNo: "2841 9912 4490",
    status: "expiring",
    validMinutesLeft: 112,
    validMinutesTotal: 2 * 24 * 60,
    note: "120 KM · WH-MUM-01 → PUNE",
  },
  {
    key: "ewb-expired",
    docType: "EWB",
    docNo: "2841 9912 4308",
    status: "expired",
    validMinutesLeft: 0,
    validMinutesTotal: 2 * 24 * 60,
    note: "VEHICLE HELD AT GATE",
  },
  {
    key: "inv-0117",
    docType: "IRN",
    docNo: "INV/2025/0117",
    status: "valid",
    validMinutesLeft: null,
    validMinutesTotal: null,
    note: "IRN + QR · ACK 162515784122990",
  },
  {
    key: "bol-maeu",
    docType: "BOL",
    docNo: "MAEU-8841-QF",
    status: "valid",
    validMinutesLeft: null,
    validMinutesTotal: null,
    note: "NHAVA SHEVA → JEBEL ALI",
  },
  {
    key: "awb-098",
    docType: "AWB",
    docNo: "098-5531 4421",
    status: "valid",
    validMinutesLeft: null,
    validMinutesTotal: null,
    note: "BOM → DXB · AI-9984",
  },
  {
    key: "lr-7782",
    docType: "LR",
    docNo: "LR-7782",
    status: "valid",
    validMinutesLeft: null,
    validMinutesTotal: null,
    note: "VRL LOGISTICS · MH-04-CD-8812",
  },
  {
    key: "rr-5521",
    docType: "RR",
    docNo: "RR-5521-0091",
    status: "valid",
    validMinutesLeft: null,
    validMinutesTotal: null,
    note: "TUGHLAKABAD → WHITEFIELD",
  },
];

/* ------------------------- statutory form fields ------------------------- */

export interface DocFormField {
  label: string;
  value: string;
}

export interface DocFormSpec {
  title: string;
  subtitle: string;
  /** Renders the IRN QR block when true. */
  qr?: boolean;
  sections: Array<{ heading: string; fields: DocFormField[] }>;
}

/** Mono field mock of the real statutory form — the page's credibility moment. */
export function docFormSpec(doc: Pick<DemoDoc, "docType" | "docNo" | "note">): DocFormSpec {
  switch (doc.docType) {
    case "EWB":
      return {
        title: "E-WAY BILL",
        subtitle: "GST FORM EWB-01 · PART A / PART B",
        sections: [
          {
            heading: "PART A",
            fields: [
              { label: "EWB NO", value: doc.docNo },
              { label: "GENERATED BY", value: "27AAFCS0441N1Z5" },
              { label: "DOC NO", value: "INV/2025/0117" },
              { label: "DOC DATE", value: "14-NOV-2025" },
              { label: "FROM GSTIN", value: "27AAFCS0441N1Z5" },
              { label: "PLACE OF DISPATCH", value: "BHIWANDI, MAHARASHTRA" },
              { label: "TO GSTIN", value: "07AAGCA2211Q1Z8" },
              { label: "PLACE OF DELIVERY", value: "DELHI NCR" },
              { label: "CONSIGNMENT VALUE", value: "₹4,86,220" },
              { label: "HSN CODE", value: "8517 · TELECOM EQUIP" },
            ],
          },
          {
            heading: "PART B",
            fields: [
              { label: "TRANSPORT MODE", value: "ROAD" },
              { label: "VEHICLE NO", value: "MH-04-CD-8812" },
              { label: "APPROX DISTANCE", value: doc.note?.split(" ")[0] ?? "440 KM" },
              { label: "TRANSPORTER ID", value: "27AAFCV8812P1Z2" },
            ],
          },
        ],
      };
    case "IRN":
    case "INV":
      return {
        title: "TAX INVOICE — e-INVOICE",
        subtitle: "GST e-INVOICE (IRN) · NIC PORTAL RETURN",
        qr: true,
        sections: [
          {
            heading: "IRN BLOCK",
            fields: [
              { label: "INVOICE NO", value: "INV/2025/0117" },
              {
                label: "IRN",
                value: "b7f9c2e1a4d80f6c3b1e9a52d7c4f8e0b6a3d1c9e7f5b2a8d4c6e1f3a9b7c5d2",
              },
              { label: "ACK NO", value: "162515784122990" },
              { label: "ACK DATE", value: "14-NOV-2025 11:42 IST" },
            ],
          },
          {
            heading: "SUPPLY",
            fields: [
              { label: "SUPPLIER GSTIN", value: "27AAFCS0441N1Z5" },
              { label: "RECIPIENT GSTIN", value: "07AAGCA2211Q1Z8" },
              { label: "TAXABLE VALUE", value: "₹4,86,220" },
              { label: "IGST @18%", value: "₹87,520" },
              { label: "INVOICE TOTAL", value: "₹5,73,740" },
            ],
          },
        ],
      };
    case "BOL":
      return {
        title: "BILL OF LADING",
        subtitle: "OCEAN TRANSPORT · NON-NEGOTIABLE COPY",
        sections: [
          {
            heading: "PARTIES",
            fields: [
              { label: "B/L NO", value: doc.docNo },
              { label: "SHIPPER", value: "STACKLINE WH-MUM-01, BHIWANDI" },
              { label: "CONSIGNEE", value: "NOVA TRADING FZE, DUBAI" },
              { label: "NOTIFY PARTY", value: "SAME AS CONSIGNEE" },
            ],
          },
          {
            heading: "CARRIAGE",
            fields: [
              { label: "VESSEL / VOYAGE", value: "MAERSK QF-8841 / V.112W" },
              { label: "PORT OF LOADING", value: "NHAVA SHEVA (INNSA1)" },
              { label: "PORT OF DISCHARGE", value: "JEBEL ALI (AEJEA)" },
              { label: "CONTAINER", value: "MSKU-8841-0 · 40FT HC" },
              { label: "ORIGINALS ISSUED", value: "3 (THREE)" },
              { label: "FREIGHT", value: "PREPAID" },
            ],
          },
        ],
      };
    case "AWB":
      return {
        title: "AIR WAYBILL",
        subtitle: "IATA FORMAT · 3-DIGIT PREFIX",
        sections: [
          {
            heading: "MAWB",
            fields: [
              { label: "AWB NO", value: doc.docNo },
              { label: "AIRLINE", value: "AIR INDIA CARGO" },
              { label: "FLIGHT / DATE", value: "AI-9984 / 15-NOV" },
              { label: "ORIGIN / DEST", value: "BOM → DXB" },
            ],
          },
          {
            heading: "CARGO",
            fields: [
              { label: "PIECES", value: "34 CTN" },
              { label: "GROSS WEIGHT", value: "421.6 KG" },
              { label: "CHARGEABLE WT", value: "612.0 KG (VOL)" },
              { label: "NATURE OF GOODS", value: "TELECOM EQUIPMENT" },
              { label: "HANDLING", value: "KEEP DRY · THIS SIDE UP" },
            ],
          },
        ],
      };
    case "LR":
      return {
        title: "LORRY RECEIPT",
        subtitle: "ROAD TRANSPORT CONSIGNMENT NOTE",
        sections: [
          {
            heading: "CONSIGNMENT",
            fields: [
              { label: "LR NO", value: doc.docNo },
              { label: "TRANSPORTER", value: "VRL LOGISTICS LTD" },
              { label: "VEHICLE NO", value: "MH-04-CD-8812" },
              { label: "FROM / TO", value: "BHIWANDI → DELHI NCR" },
              { label: "PACKAGES", value: "38 CTN + 6 PLT" },
              { label: "FREIGHT BASIS", value: "TO PAY" },
            ],
          },
        ],
      };
    case "RR":
      return {
        title: "RAILWAY RECEIPT",
        subtitle: "INDIAN RAILWAYS · GOODS TARIFF",
        sections: [
          {
            heading: "RECEIPT",
            fields: [
              { label: "RR NO", value: doc.docNo },
              { label: "FROM STATION", value: "TUGHLAKABAD (TKD)" },
              { label: "TO STATION", value: "WHITEFIELD (WFD)" },
              { label: "WAGON / RAKE", value: "BCN HL · 42 WAGONS" },
              { label: "WEIGHT CHARGED", value: "16,000 KG" },
              { label: "FREIGHT", value: "₹1,28,400 · PAID" },
            ],
          },
        ],
      };
    default:
      return {
        title: DOC_TYPE_LABEL[doc.docType] ?? doc.docType,
        subtitle: "AUTO-GENERATED · ATTACHED TO SHIPMENT",
        sections: [
          {
            heading: "DOCUMENT",
            fields: [
              { label: "DOC NO", value: doc.docNo || "—" },
              { label: "SHIPMENT", value: "INV/2025/0117 → DEL-NCR" },
              { label: "GENERATED", value: "AT INVOICE TIME" },
              { label: "SOURCE", value: "ERPNEXT · AUTO-ATTACHED" },
            ],
          },
        ],
      };
  }
}

/* ------------------------- method → doc set (Section 2) ------------------------- */

export interface MethodDocSet {
  method: ShippingMethod;
  docs: Array<{ key: string; label: string; refKey?: string; to?: string }>;
  rule: string;
}

export const METHOD_DOC_SETS: MethodDocSet[] = [
  {
    method: "road",
    docs: [
      { key: "inv", label: "TAX INVOICE + IRN/QR", refKey: "inv-0117" },
      { key: "ewb", label: "E-WAY BILL ✓ VALID 22H", refKey: "ewb-valid" },
      { key: "lr", label: "LR", refKey: "lr-7782" },
      { key: "pl", label: "PACKING LIST" },
      { key: "gp", label: "GATE PASS" },
    ],
    rule: "EWB REQUIRED IF CONSIGNMENT > ₹50,000 · VALIDITY = 1 DAY / 100 KM + 1",
  },
  {
    method: "air",
    docs: [
      { key: "inv", label: "TAX INVOICE + IRN", refKey: "inv-0117" },
      { key: "awb", label: "AWB 098-5531 4421", refKey: "awb-098" },
      { key: "ewb", label: "E-WAY BILL (FIRST/LAST MILE)", refKey: "ewb-valid" },
      { key: "pl", label: "PACKING LIST" },
      { key: "dg", label: "DG DECLARATION (IF APPLICABLE)" },
    ],
    rule: "AWB IATA 3-DIGIT PREFIX · CHARGEABLE WT = MAX(ACTUAL, VOLUMETRIC)",
  },
  {
    method: "sea",
    docs: [
      { key: "cinv", label: "COMMERCIAL INVOICE", refKey: "inv-0117" },
      { key: "bol", label: "B/L MAEU-8841-QF", refKey: "bol-maeu" },
      { key: "pl", label: "PACKING LIST" },
      { key: "sb", label: "SHIPPING BILL (EXPORT)" },
      { key: "clp", label: "CONTAINER LOAD PLAN →", to: "/transport" },
    ],
    rule: "B/L ORIGINALS 3 + NON-NEGOTIABLE COPIES · FCL → CONTAINER LOAD PLAN",
  },
  {
    method: "rail",
    docs: [
      { key: "inv", label: "TAX INVOICE + IRN", refKey: "inv-0117" },
      { key: "ewb", label: "E-WAY BILL", refKey: "ewb-valid" },
      { key: "rr", label: "RR (RAILWAY RECEIPT)", refKey: "rr-5521" },
      { key: "gp", label: "GATE PASS" },
    ],
    rule: "RR IS TITLE DOCUMENT · EWB STILL APPLIES FOR ROAD LEGS",
  },
];

/** Compliance rulebook rows (Section 6). */
export const RULEBOOK: Array<{ rule: string; plain: string }> = [
  {
    rule: "EWB THRESHOLD ₹50,000 / CONSIGNMENT",
    plain:
      "Any movement of goods worth more than ₹50,000 needs an e-way bill before the vehicle moves. Stackline totals the invoice at generation time and fires the EWB call automatically — no manual check.",
  },
  {
    rule: "EWB VALIDITY 1 DAY PER 100 KM (+1)",
    plain:
      "Validity is one day per 100 km of declared distance, plus one day. Stackline stores the distance on the doc and starts a live countdown; at 6 hours left the shipment is flagged for extension or re-generation.",
  },
  {
    rule: "E-INVOICE MANDATE TURNOVER ≥ ₹5Cr",
    plain:
      "Businesses above ₹5 crore annual turnover must clear B2B invoices through the IRP and carry the IRN + signed QR on the invoice. The IRN call is part of the invoice submit — one motion, no portal copy-paste.",
  },
  {
    rule: "B/L ORIGINALS 3 + NON-NEGOTIABLE COPIES",
    plain:
      "Ocean bills of lading are issued in three signed originals; any one surrendered releases the cargo. Stackline tracks which originals are where, alongside non-negotiable copies for the file.",
  },
  {
    rule: "AWB IATA FORMAT 3-DIGIT PREFIX",
    plain:
      "Air waybills use the IATA 3-digit airline prefix plus an 8-digit serial (e.g. 098-5531 4421). The format is validated at entry so a mistyped AWB never reaches the airline.",
  },
  {
    rule: "RR = TITLE DOCUMENT FOR RAIL",
    plain:
      "For rail consignments the railway receipt is the document of title — the consignee takes delivery against it. Stackline attaches the RR to the shipment and the gate pass so the handover chain is auditable.",
  },
];

/* ------------------------- invoice flow chain (Section 5) ------------------------- */

export const INVOICE_CHAIN: Array<{ id: string; label: string; chip: string; tone: "brand" | "data" }> = [
  { id: "dn", label: "DELIVERY NOTE", chip: "DN-2025-0117", tone: "brand" },
  { id: "si", label: "SALES INVOICE", chip: "INV/2025/0117", tone: "brand" },
  { id: "irn", label: "E-INVOICE (IRN + QR)", chip: "ACK ✓ 1 CALL", tone: "data" },
  { id: "ewb", label: "E-WAY BILL", chip: "EWB 2841 9912 4471", tone: "data" },
  { id: "att", label: "ATTACHED TO SHIPMENT", chip: "GP-2841 BUNDLE", tone: "data" },
];

export const ERPNEXT_DOCTYPES =
  "Delivery Note / Sales Invoice / e-Invoice Settings / E-Way Bill Log / Packing Slip";
